# Generated by Django 2.0 on 2017-12-27 18:36

from django.db import migrations, models
import macaddress.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Computer', max_length=100)),
                ('mac', macaddress.fields.MACAddressField(default='00:12:3c:37:64:8f', integer=True)),
                ('secret', models.CharField(default='0a1b3c4d5e6f', max_length=12)),
                ('description', models.TextField(default='This is a dank-ass description for a dank-af device')),
                ('target_address', models.GenericIPAddressField(default='255.255.255.255')),
                ('target_port', models.SmallIntegerField(default=9)),
                ('listener', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listener_address', models.GenericIPAddressField(default='0.0.0.0')),
                ('listener_port', models.SmallIntegerField(default=9)),
                ('packet_count', models.SmallIntegerField(default=3)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
