# Generated by Django 2.0 on 2017-12-27 16:53

from django.db import migrations, models
import macaddress.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mac', macaddress.fields.MACAddressField(integer=True)),
                ('secret', models.CharField(max_length=12)),
                ('description', models.TextField()),
                ('target_address', models.GenericIPAddressField(default='255.255.255.255')),
                ('target_port', models.SmallIntegerField(default=9)),
                ('listener', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listener_address', models.GenericIPAddressField()),
                ('listener_port', models.SmallIntegerField()),
            ],
        ),
    ]
