# Generated by Django 2.0 on 2017-12-27 16:57

from django.db import migrations
import macaddress.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='mac',
            field=macaddress.fields.MACAddressField(default='00:12:3c:37:64:8f', integer=True),
        ),
    ]
