# Generated by Django 2.0 on 2017-12-27 16:59

from django.db import migrations, models
import macaddress.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20171227_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='description',
            field=models.TextField(default='This is a dank-ass description for a dank-af device'),
        ),
        migrations.AlterField(
            model_name='device',
            name='mac',
            field=macaddress.fields.MACAddressField(default='00:12:3c:37:64:8f', integer=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(default='Computer', max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='secret',
            field=models.CharField(default='0a1b3c4d5e6f', max_length=12),
        ),
    ]
