# Generated by Django 2.0 on 2017-12-27 18:10

from django.db import migrations, models
import macaddress.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20171227_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Global',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listener_address', models.GenericIPAddressField()),
                ('listener_port', models.SmallIntegerField()),
                ('sent_packets', models.SmallIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Setting',
        ),
        migrations.AlterField(
            model_name='device',
            name='mac',
            field=macaddress.fields.MACAddressField(default='00:12:3c:37:64:8f', integer=True),
        ),
    ]
